[book]
title = "Let's Build a Compiler"
authors = ["Jack W. Crenshaw"]
src = "src"
language = "en"
multilingual = false

[output.html]
curly-quotes = true
additional-js = ["highlight.js"]
git-repository-url = "https://github.com/xmonader/letsbuildacompiler-pretty"
